name: ${artifactId}
version: ${version}
description: This is a simple Bukkit Plugin
author: ${author}

main: ${package}.Main

commands:
  Hello:
    description: Shows a hello message to the player
    usage: |
      /<command> shows a hello message to the player